#! /bin/sh
### BEGIN INIT INFO
# Provides:          logmein-hamachi
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop logmein-hamachi engine
### END INIT INFO
#
# Author: LogMeIn, Inc. <hamachilinux-feedback@logmein.com>
#

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="LogMeIn Hamachi VPN tunneling engine"
NAME=logmein-hamachi
DAEMON=/opt/logmein-hamachi/bin/hamachid
DNAME=hamachid
PIDFILE=/var/run/logmein-hamachi/hamachid.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 5

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Define LSB log_* functions. Depend on lsb-base (>= 3.0-6)
#. /lib/lsb/init-functions
# using echo instead lsb's log_*


# start the daemon/service

do_start()
{
    # Return
    #   0 if daemon has been started
    #   1 if daemon was already running
    #   2 if daemon could not be started

    if [ -e $PIDFILE ] ; then
        echo "already running"
	return 1
    fi
    $DAEMON &
    # start_daemon -p $PIDFILE $DAEMON

    return "$?"
}

# stop the daemon/service

do_stop()
{
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred

    # killproc -p $PIDFILE $DAEMON
    killall $DNAME

	# it needs some time for the engine to close all things and exit
	sleep 3

    RETVAL="$?"
    # [ "$RETVAL" = 2 ] && return 2

    # remove pidfile if daemon could not delete on exit.
    rm -f $PIDFILE

    return "$RETVAL"
}

case "$1" in
  start)
    echo -n "Starting $DESC $NAME"

    do_start

    echo

    case "$?" in
        0|1) echo "starting - success" ;;
        *)   echo "starting - failed" ;;
    esac
    ;;
  stop)
    echo -n "Stopping $DESC $NAME"

    do_stop

    echo

    case "$?" in
        0|1) echo "stopping - success" ;;
        2)   echo "stopping - failed" ;;
    esac
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC $NAME"


    do_stop

    echo

    case "$?" in
      0|1)
        sleep 1
        do_start

        case "$?" in
            0) echo "starting - success" ;;
            1) echo "starting - failed, old process is still running" ;; # Old process is still running
            *) echo "starting - failed" ;; # Failed to start
        esac
        ;;
      *)
          # Failed to stop
        echo "stopping - failed"
        ;;
    esac
    ;;
  *)

    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

:
